// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY5VR5BjIJjhm68C9KUHmVRG9BA8R3PPk',
    appId: '1:639047425357:web:1528a96bf18b2144eeeb04',
    messagingSenderId: '639047425357',
    projectId: 'flutter-caht-app-541fe',
    authDomain: 'flutter-caht-app-541fe.firebaseapp.com',
    storageBucket: 'flutter-caht-app-541fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIwN4bsHftQAo7j0a8A7cb0iy32ux3wbc',
    appId: '1:639047425357:android:25ee668c99e99963eeeb04',
    messagingSenderId: '639047425357',
    projectId: 'flutter-caht-app-541fe',
    storageBucket: 'flutter-caht-app-541fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Y5lF0dBPVjDPPLUbgpZ2gOpyW33_a3c',
    appId: '1:639047425357:ios:33fadb0c0a6bc2cbeeeb04',
    messagingSenderId: '639047425357',
    projectId: 'flutter-caht-app-541fe',
    storageBucket: 'flutter-caht-app-541fe.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Y5lF0dBPVjDPPLUbgpZ2gOpyW33_a3c',
    appId: '1:639047425357:ios:454339b35f9d0532eeeb04',
    messagingSenderId: '639047425357',
    projectId: 'flutter-caht-app-541fe',
    storageBucket: 'flutter-caht-app-541fe.appspot.com',
    iosBundleId: 'com.example.mychatapp.RunnerTests',
  );
}
